# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20170607_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loans.Business'),
        ),
        migrations.AlterField(
            model_name='business',
            name='registered_company',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
